backend:
  name: github
  repo: aleksivuorela/portfolio

media_folder: static/img
public_folder: img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/intro/index.md"
        label: "Intro"
        name: "intro"
        fields:
          - {label: "Key", name: "key", widget: "hidden", default: "intro"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Subtitle", name: "subtitle", widget: "string"}
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Key", name: "key", widget: "hidden", default: "about"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/experience/index.md"
        label: "Experience"
        name: "experience"
        fields:
          - {label: "Key", name: "key", widget: "hidden", default: "experience"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Jobs", name: "jobs", widget: "list", fields: [
              {label: Employer, name: employer, widget: string},
              {label: Position, name: position, widget: string},
              {label: Start date, name: start_date, widget: date},
              {label: End date, name: end_date, widget: date},
              {label: Description, name: description, widget: markdown},
              {label: "Logo", name: "logo", widget: "object", fields: [
                  {label: "Image", name: "image", widget: "image"},
                  {label: "Alt", name: "alt", widget: "string"}
                ]}
            ]}